/* PolyTrack Unified: integration UI. Existing MisoTweaks owns clips and game settings. */
(()=>{'use strict';
const core=window.PolyModCore,api=()=>window.__misoClipApi,live=()=>window.__misoLiveInputs;
const defaults={picker:'KeyV',replay:'KeyB',library:'F4',saveState:'F6',loadState:'F7',clearState:'F8',tas:'F9',more:'F10',driveStop:'F11'};
let settings;try{settings=JSON.parse(localStorage.getItem('poly-unified-settings')||'{}');}catch{settings={};}
settings.bindings={...defaults,...settings.bindings};settings.releaseMs=Math.max(0,Math.min(500,Number(settings.releaseMs??40)||0));
const persist=()=>localStorage.setItem('poly-unified-settings',JSON.stringify(settings));
const binding=k=>settings.bindings[k];let modal=null,modalClose=null,capture=null,checkpoint=null,libraryGhosts=false;
const gate=core.soundGate(()=>settings.releaseMs);
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function button(text,fn){const b=el('button',text,'button');b.type='button';b.onclick=()=>Promise.resolve().then(fn).catch(error);return b;}
function error(e){const p=modal?.querySelector('.poly-error');if(p)p.textContent=e.message||String(e);else alert(e.message||String(e));}
function close(restore=false){const callback=modalClose;modal?.remove();modal=null;modalClose=null;if(restore)callback?.();}
function dialog(title,onClose){window.__polyReleaseControls?.();close();const bg=el('div',undefined,'poly-modal'),panel=el('section',undefined,'poly-panel');bg.setAttribute('role','dialog');bg.setAttribute('aria-modal','true');bg.setAttribute('aria-label',title);panel.append(el('h2',title));bg.append(panel);document.getElementById("ui").append(bg);modal=bg;modalClose=onClose||null;return panel;}
function footer(panel,buttons){const row=el('div',undefined,'poly-row');for(const b of buttons)row.append(b);panel.append(el('p','','poly-error'),row);}
function nameClip(auto,save){const panel=dialog('Save clip'),input=el('input');input.placeholder=auto;input.setAttribute('aria-label','Clip name');panel.append(el('p','Name your clip, or leave this blank to use the automatic name.'),input);const commit=()=>{const value=input.value;close();save(value);};footer(panel,[button('Cancel',close),button('Save',commit)]);input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();commit();}};input.focus();}
function textBox(title,value,editable,done){const panel=dialog(title),input=el('textarea');input.value=value;input.readOnly=!editable;input.setAttribute('aria-label',title);panel.append(input);footer(panel,[button('Back',close),button(editable?'Save':'Copy',async()=>{if(editable){const value=input.value;close();await done(value);}else{try{await navigator.clipboard.writeText(input.value);}catch{input.select();}}})]);input.focus();}
async function ghostClips(){const ghosts=await window.__polySelectedGhosts?.()||[];return ghosts.map(g=>({...fromRecording(g.recording,g.time.numberOfFrames,g.nickname,g.carStyle?.serialize?.()),trackId:window.__polySelectedTrackId}));}
function fromRecording(recording,frames,name,style){const p=window.__clipPako.Ay||window.__clipPako;const raw=api().base64ToBytes(recording.serialize().replace(/-/g,'+').replace(/_/g,'/'));const inf=new p.Inflate();inf.push(raw,true);if(inf.err)throw Error('Could not decode the ghost inputs.');const track=window.__getCurrentTrack?.();return {id:'clip_'+crypto.randomUUID(),name:name||'Ghost',playerName:name||'Ghost',frames,carStyle:style||'',trackId:track?.getId?.()||window.__polySelectedTrackId||'',recordingBytes:api().bytesToBase64(inf.result),createdAt:Date.now()};}
function openLibrary(onClose,withGhosts=false){
 libraryGhosts=withGhosts;api().ensureStyles();const panel=dialog('Clips',onClose);panel.className='clip-menu-bg poly-library';panel.querySelector('h2').textContent='Your Clips:';const nav=el('div',undefined,'poly-row'),crumb=el('span','Maps'),search=el('input'),list=el('div',undefined,'clip-menu-container'),selected=new Set();let folder=null;
 search.type='search';search.placeholder='Search maps';search.setAttribute('aria-label','Search maps');const back=button('All maps',()=>{folder=null;search.value='';render();});nav.append(back,crumb);panel.append(nav,search,list);const status=el('p','','poly-note');panel.append(status);
 const chosen=()=>api().list().filter(c=>selected.has(c.id));const one=()=>{const c=chosen();if(c.length!==1)throw Error('Select one clip.');return c[0];};
 function render(){list.replaceChildren();back.hidden=folder===null;search.placeholder=folder===null?'Search maps':'Search clip names';search.setAttribute('aria-label',search.placeholder);const groups=core.folders(api().list(),api().trackName);const group=groups.find(g=>g.id===folder);crumb.textContent=group?.name||'Maps';
 const items=folder===null?core.filter(groups,search.value):core.filter(group?.clips||[],search.value);for(const item of items){const b=button('',()=>{if(folder===null){folder=item.id;search.value='';render();search.focus();}else{selected.has(item.id)?selected.delete(item.id):selected.add(item.id);render();}});b.classList.add('clip-menu-entry');b.append(el('h2',item.name),el('p',folder===null?`${item.clips.length} clips`:`${group.name} · ${api().formatDuration(item.frames)}`));if(folder!==null){b.setAttribute('aria-pressed',String(selected.has(item.id)));b.classList.toggle('selected',selected.has(item.id));const check=el('img',undefined,'checkmark');check.src='images/checkmark.svg';b.append(check);}list.append(b);}if(!items.length)list.append(el('p','No matches.'));status.textContent=selected.size?`${selected.size} selected${withGhosts?' · Watch with selected leaderboard ghosts':''}`:'Select clips from any map folder.';}
 footer(panel,[button('Close',()=>close(true)),button('Recent runs',()=>openRecentRuns(onClose,withGhosts)),button('Convert inputs',()=>{close();live().openConverter();}),button('Stop replay',()=>live().stop()),button('Import',()=>textBox('Import MisoClip','',true,code=>{const c=api().decode(code.trim());if(!c)throw Error('Invalid MisoClip.');c.id='clip_'+crypto.randomUUID();if(!api().add(c))throw Error('Clip storage is full.');openLibrary(onClose,withGhosts);})),button('Watch',async()=>{const c=chosen();if(!c.length)throw Error('Select at least one clip.');if(!window.__polySelectedTrackId&&!window.__getCurrentTrack?.())throw Error('Open a map first.');await api().watch(c,withGhosts);close();}),button('Arm replay',()=>{live().startClip({...one(),mapLocked:false});close();}),button('More',()=>moreClip(one())),button('Export',()=>textBox('Export MisoClip',api().encode(one()),false)),button('Rename',()=>{const c=one();nameClip(c.name,name=>{if(name.trim())api().rename(c.id,name.trim());openLibrary(onClose,withGhosts);});}),button('Delete',()=>{const c=one();if(!api().remove(c.id))throw Error('Could not delete clip.');selected.delete(c.id);render();})]);panel.lastElementChild.className='clip-menu-wrapper';for(const b of panel.lastElementChild.children){const icons={Close:'back','Recent runs':'timer',Watch:'play',Import:'import',Export:'share',Rename:'editor',Delete:'cancel'};if(icons[b.textContent]){const img=el('img',undefined,'button-icon');img.src='images/'+icons[b.textContent]+'.svg';b.prepend(img,document.createTextNode(' '));}if(b.textContent.trim()==='Close')b.classList.add('back');}search.oninput=render;render();search.focus();
}
function openRecentRuns(onClose,withGhosts=false){
 const panel=dialog('Recent runs',()=>openLibrary(onClose,withGhosts));panel.className='clip-menu-bg poly-library';panel.querySelector('h2').textContent='Recent Runs:';const list=el('div',undefined,'clip-menu-container'),runs=api().recent(),selected={run:null};panel.append(list);
 runs.forEach((run,index)=>{const b=button('',()=>{for(const entry of list.children)entry.classList.remove('selected');selected.run=run;b.classList.add('selected');});b.classList.add('clip-menu-entry');b.append(el('h2',`${index+1}. ${run.trackName||api().trackName(run.trackId)||'Unknown map'} · ${api().formatDuration(run.frames)}`),el('p',`${run.completed===true?'Finished':'Unfinished'} · ${new Date(run.createdAt).toLocaleString()}`));const check=el('img',undefined,'checkmark');check.src='images/checkmark.svg';b.append(check);list.append(b);});
 if(!runs.length)list.append(el('p','Your five most recent runs will appear here, including unfinished attempts.'));
 const one=()=>{if(!selected.run)throw Error('Select a recent run.');return selected.run;};footer(panel,[button('Back',()=>close(true)),button('Watch',async()=>{await api().watch([one()],false);close();}),button('Save as MisoClip',()=>{const run=one();nameClip(run.name,name=>{if(!api().saveRecent(run.id,name))throw Error('Clip storage is full.');openRecentRuns(onClose,withGhosts);});})]);panel.lastElementChild.className='clip-menu-wrapper';for(const b of panel.lastElementChild.children){const icon=b.textContent==='Back'?'back':b.textContent==='Watch'?'play':b.textContent==='Save as MisoClip'?'save':null;if(icon){const img=el('img',undefined,'button-icon');img.src='images/'+icon+'.svg';b.prepend(img,document.createTextNode(' '));}if(b.textContent.trim()==='Back')b.classList.add('back');}
}
function moreClip(clip){const panel=dialog(clip.name||'More');footer(panel,[button('Back',close),button('Extract Inputs',()=>{close();live().openExtractor(clip);}),button('Convert to MisoClip',()=>{nameClip(clip.name,name=>{if(!api().add({...clip,id:'clip_'+crypto.randomUUID(),name:name.trim()||clip.name,mapLocked:false,accountBound:false}))throw Error('Clip storage is full.');});}),button('Savestate from point',()=>pointPicker(clip))]);}
async function moreGhost(){const clips=await ghostClips();if(!clips.length)throw Error('Select a ghost on the leaderboard first.');if(clips.length===1)return moreClip(clips[0]);const p=dialog('Choose a ghost');for(const c of clips)p.append(button(c.name,()=>moreClip(c)));footer(p,[button('Close',close)]);}
async function pointPicker(clip){close();document.querySelector('.poly-point')?.remove();await api().watch([clip],false);const dock=el('div',undefined,'poly-point'),slider=el('input'),number=el('input'),label=el('label','Checkpoint (ms)');slider.type='range';slider.min=0;slider.max=Math.max(0,clip.frames-1);slider.step=1;number.type='number';number.min=0;number.max=slider.max;slider.value=number.value=0;slider.setAttribute('aria-label','Checkpoint time');number.setAttribute('aria-label','Checkpoint milliseconds');const seek=value=>{const at=core.clampFrame(value,clip.frames);number.value=slider.value=at;window.__polySeek?.(at);};slider.oninput=()=>seek(slider.value);number.onchange=()=>seek(number.value);dock.append(label,slider,number,button('Use current time',()=>seek(window.__polyReplayTime?.()??number.value)),button('Practice here',()=>{const frame=core.clampFrame(number.value,clip.frames);checkpoint={clip,frame,trackId:window.__polySelectedTrackId||clip.trackId};dock.remove();resumeCheckpoint();}),button('Close',()=>dock.remove()));document.body.append(dock);}
function saveState(){if(document.querySelector('.poly-replay-view'))throw Error('Use More → Savestate from point while watching a run.');const car=window.__getPlayerState?.();if(!car?.hasStarted()||car.hasFinished())throw Error('Start driving before saving a checkpoint.');checkpoint={clip:fromRecording(car.getRecording(),car.getTime().numberOfFrames,'Practice checkpoint',car.getCarStyle()?.serialize?.()),frame:car.getTime().numberOfFrames,trackId:window.__getCurrentTrack()?.getId()};}
function resumeCheckpoint(){if(!checkpoint)throw Error('Save a checkpoint first.');const id=document.querySelector('.game-ui:not(.poly-replay-view)')?window.__getCurrentTrack?.()?.getId():window.__polySelectedTrackId;if(id!==checkpoint.trackId)throw Error('Open the checkpoint’s map before restoring it.');live().stop({restart:false});window.__polyPracticePending={recording:live().recordingFromClip(checkpoint.clip),frame:checkpoint.frame};if(document.querySelector('.game-ui:not(.poly-replay-view)')&&window.__misoRestartCurrentRun)window.__misoRestartCurrentRun();else window.__polyPlayCurrent?.([]);}
async function openTas(){
 if(!window.electron?.openTasTool)throw Error('Open the desktop app to use the TAS editor.');
 const webPopup=!!window.electron.webMode;if(webPopup)window.electron.openTasTool();
 let rec;
 if(document.querySelector('.poly-replay-view'))rec=window.__polyReplayRecord?.();
 else{const ghosts=await ghostClips();rec=ghosts.length?live().recordingFromClip(ghosts[0]):window.__getPlayerState?.()?.getRecording();if(ghosts.length)await api().watch(ghosts,false);else if(!document.querySelector('.game-ui:not(.poly-replay-view)'))window.__polyPlayCurrent?.([]);}
 if(rec)window.electron.setTasRecording(rec.serialize());
 if(document.querySelector('.poly-replay-view'))window.electron.setTasGhosts(window.__polyReplayGhostData());else window.electron.setTasGhosts({names:[],visibility:[],selected:-1});
 if(!webPopup)window.electron.openTasTool();
}
function installSettings(container){
 const heading=el('h3','Mods · Keybinds');container.append(heading);
 const actions=[['picker','Replay picker'],['replay','Start / stop replay'],['library','Clips library'],['save','Save clip'],['saveState','Save checkpoint'],['loadState','Restore checkpoint'],['clearState','Clear checkpoint'],['tas','TAS editor'],['more','Ghost options'],['driveStop','Finish TAS continuation']];
 for(const [id,label]of actions){const row=el('div',undefined,'poly-key-row'),b=button('',()=>{capture={id,button:b};b.textContent='Press a key…';});b.textContent=(id==='save'?api()?.getSaveKey():binding(id))||'KeyC';row.append(el('p',label),b);container.append(row);}
 const header=el('h3','Replay sounds'),row=el('div',undefined,'poly-key-row'),slider=el('input'),value=el('output',`${settings.releaseMs} ms`);slider.type='range';slider.min=0;slider.max=500;slider.step=1;slider.value=settings.releaseMs;slider.setAttribute('aria-label','Minimum hold time for release sound in milliseconds');slider.oninput=()=>{settings.releaseMs=Number(slider.value);value.textContent=`${settings.releaseMs} ms`;persist();};row.append(el('p','Minimum hold for release sound'),slider,value);container.append(header,row);
}
// Runs before game handlers. Modal text and navigation never become driving inputs.
window.addEventListener('keydown',e=>{
 if(capture){e.preventDefault();e.stopImmediatePropagation();const c=capture;if(e.code==='Escape'){capture=null;c.button.textContent=c.id==='save'?api().getSaveKey():binding(c.id);return;}if(e.repeat||e.ctrlKey||e.metaKey||e.altKey)return;const conflict=Object.entries(settings.bindings).find(([id,key])=>id!==c.id&&key===e.code);if(conflict){c.button.textContent=`Used by ${conflict[0]}`;return;}if(c.id==='save')api().setSaveKey(e.code);else settings.bindings[c.id]=e.code;if(c.id==='replay')live()?.setTriggerKey(e.code);persist();c.button.textContent=e.code;capture=null;return;}
 const target=e.target,typing=target?.matches?.('input,textarea,[contenteditable=true]');const blocked=modal||target?.closest?.('.poly-point')||document.querySelector('.miso-live-overlay,.clip-box-bg');
 if(blocked){e.stopImmediatePropagation();if(e.code==='Escape'){e.preventDefault();if(modal)close(true);else {live()?.close?.();document.querySelector('.poly-point')?.remove();}}if(typing&&e.code==='Enter')target.onkeydown?.(e);return;}
 if(typing){e.stopImmediatePropagation();return;}
 if(e.repeat||e.ctrlKey||e.metaKey||e.altKey)return;
 if(e.code===api()?.getSaveKey()){e.preventDefault();e.stopImmediatePropagation();api().create();return;}
 const action=Object.keys(defaults).find(k=>binding(k)===e.code);const handlers={library:()=>openLibrary(),saveState,loadState:resumeCheckpoint,clearState:()=>{checkpoint=null;},tas:openTas,more:moreGhost,driveStop:stopDrive};
 if(handlers[action]){e.preventDefault();e.stopImmediatePropagation();Promise.resolve().then(handlers[action]).catch(error);}
},true);
window.addEventListener('keyup',e=>{if(modal||capture||e.target?.matches?.('input,textarea,[contenteditable=true]'))e.stopImmediatePropagation();},true);
function decorate(){
 for(const watch of document.querySelectorAll('button.watch')){if(watch.dataset.polyEnhanced)continue;watch.dataset.polyEnhanced='true';const parent=watch.parentNode;const action=(name,fn,icon)=>{const b=button(name,fn);b.className=watch.className.replace(/\bwatch\b/g,'poly-game-action');b.style.cssText=watch.style.cssText;const img=el('img',undefined,'button-icon');img.src='images/'+icon+'.svg';b.append(document.createTextNode(' '),img);return b;};parent.insertBefore(action('More',moreGhost,'list'),watch);parent.insertBefore(action('TAS Editor',openTas,'editor'),watch);parent.insertBefore(action('Clips',()=>openLibrary(undefined,true),'play'),watch.nextSibling);}
 for(const btn of document.querySelectorAll('.track-selection-ui .bar button')){if(btn.textContent.trim()!=='Import'||btn.dataset.polyIndex)continue;btn.dataset.polyIndex='true';const b=button('PT Index',openIndex);b.classList.add('poly-index');btn.parentNode.insertBefore(b,btn);}
}
async function openIndex(){const panel=dialog('PT Index'),tabs=el('div',undefined,'poly-row'),search=el('input'),list=el('div',undefined,'poly-list'),note=el('p','Loading…','poly-note');search.type='search';search.placeholder='Search players';search.setAttribute('aria-label','Search PT Index players');panel.append(tabs,search,note,list);let selected='normal',rows=[],request=0;
 function render(){list.replaceChildren();const table=el('table'),head=el('thead'),tr=el('tr');for(const x of ['Rank','Player','Points','Maps'])tr.append(el('th',x));head.append(tr);table.append(head);const body=el('tbody');for(const r of core.filter(rows,search.value,'nickname').slice(0,500)){const tr=el('tr');for(const x of [r.rank,r.nickname,Math.round(r.points).toLocaleString(),r.maps])tr.append(el('td',x));body.append(tr);}table.append(body);list.append(table);}
 async function load(kind,refresh=false){selected=kind;const token=++request;note.textContent='Loading…';try{const snapshot=await (refresh?window.PolyIndexData.refresh(kind,(done,total)=>{if(token===request)note.textContent=`Refreshing ${done}/${total} maps…`;}):window.PolyIndexData.load(kind));if(token!==request)return;rows=window.PolyIndexRanking.rank(snapshot,kind);note.textContent=`Snapshot ${new Date(snapshot.generatedAt).toLocaleString()} · ${rows.length} players`;render();}catch(e){note.textContent=e.message;}}
 tabs.append(button('Main+CT',()=>load('normal')),button('Kacky',()=>load('kacky')));footer(panel,[button('Close',close),button('Refresh',()=>load(selected,true))]);search.oninput=render;load('normal');}
window.addEventListener('poly-native-error',e=>error(Error(e.detail)));
window.PolyMods={binding,nameClip,openLibrary,installSettings,moreGhost,resetSounds:()=>gate.reset(),shouldSound:(key,pressed,ms)=>gate.edge(key,pressed,ms),openTas,updateReplayControls};
function updateReplayControls(){const b=document.getElementById('submit-tas-button');if(b)b.disabled=!window.__polyReplaySelected?.()?.car?.hasFinished();}
window.addEventListener('poly-replay-ready',()=>{
 const root=document.querySelector('.poly-replay-view');if(!root)return;
 const actions=el('div',undefined,'poly-replay-actions'),editor=button('Editor',openTas),submit=button('Submit TAS',()=>{const ghost=window.__polyReplaySelected();if(!ghost?.car.hasFinished())throw Error('The selected replay must finish first.');const time=ghost.car.getFinishTime();const p=dialog('Submit TAS');p.append(el('p','Submit this completed run ('+api().formatDuration(time.numberOfFrames)+') to the leaderboard?'));footer(p,[button('Cancel',close),button('Submit',async()=>{const result=await window.__polySubmitReplay(time,ghost.settings.recording);if(!result)throw Error('The server did not confirm submission. Check your profile and connection.');p.querySelector('p').textContent='Run submitted.';p.lastElementChild.replaceChildren(button('Close',close));})]);});editor.id='poly-editor-button';submit.id='submit-tas-button';actions.append(editor,submit);root.querySelector(".time-bar-ui").append(actions);
 const speed=el('div',undefined,'poly-replay-speed'),select=el('select');select.setAttribute('aria-label','Replay speed');for(const rate of [.05,.1,.25,.5,.75,1,1.5,2,3,4]){const option=el('option',rate+'×');option.value=rate;select.append(option);}select.value=window.__polyReplayRate||1;select.onchange=()=>window.__polyReplayRate=Number(select.value);speed.append(el('label','Speed'),select);root.querySelector(".time-bar-ui").insertBefore(speed,root.querySelector(".time-bar-ui>.bar"));updateReplayControls();
});
let driveSession=null,driveTimer=null;
function stopDrive(payload){if(!driveSession)return;clearInterval(driveTimer);const car=window.__getPlayerState?.(),rec=car?.getRecording();window.__setSimSpeed?.(1);window.electron.tasToolDriveStatus({status:payload?.commit===false?'aborted':'stopped',frames:car?.getTime()?.numberOfFrames,sessionId:driveSession.sessionId,encoded:payload?.commit===false?driveSession.encoded:rec?.serialize?.()||''});driveSession=null;}
window.addEventListener('DOMContentLoaded',()=>{
 new MutationObserver(decorate).observe(document.getElementById('ui'),{childList:true,subtree:true});decorate();live()?.setTriggerKey(binding('replay'));
 window.electron?.onTasToolApply?.(encoded=>{try{const record=window.__clipRecordingClass.deserialize(encoded);if(!record)throw Error('Invalid TAS recording.');const events=window.MisoClipTools.eventsFromRecordingBytes(api().recordingBytes(fromRecording(record,1,'TAS')),0xffffff);const duration=Math.max(1000,...events.events.map(x=>x.at))+1000;if(!document.querySelector('.poly-replay-view'))throw Error('Open a replay before applying TAS inputs.');window.__polyApplyReplay(record,duration);}catch(e){error(e);}});
 window.electron?.onTasToolBruteforceContextRequest?.(payload=>{try{const context=window.__polyLastNativeContext;if(!context)throw Error('Press Watch or Play on the selected map before starting BruteForce.');window.electron.tasToolBruteforceContext({...context,physicsInit:window.__polyTasPhysicsInit,runId:payload.runId});}catch(e){window.electron.tasToolBruteforceContext({runId:payload.runId,error:e.message});}});
 window.electron?.onTasToolDriveStart?.(payload=>{try{
  const record=window.__clipRecordingClass.deserialize(payload.encoded);if(!record)throw Error('Invalid TAS recording.');
  window.electron.tasToolDriveStatus({status:'received',sessionId:payload.sessionId});
  const frame=Math.max(0,Math.min(0xffffff,Math.floor(Number(payload.takeoverFrame)||0)));
  checkpoint={clip:fromRecording(record,frame+1,'TAS continuation'),frame,trackId:window.__polySelectedTrackId||window.__getCurrentTrack?.()?.getId()};
  driveSession=payload;resumeCheckpoint();window.__setSimSpeed?.(Number(payload.rate)||1);
  window.electron.tasToolDriveStatus({status:'preroll',sessionId:payload.sessionId,takeoverFrame:frame});
  clearInterval(driveTimer);driveTimer=setInterval(()=>{if(window.__getPlayerState?.()?.getTime()?.numberOfFrames>=frame){clearInterval(driveTimer);window.electron.tasToolDriveStatus({status:'driving',sessionId:payload.sessionId});}},100);
 }catch(e){window.electron.tasToolDriveStatus({status:'error',sessionId:payload.sessionId,message:e.message});}});
 window.electron?.onTasToolDriveStop?.(stopDrive);
 window.electron?.onTasToolSetVisibility?.(values=>{if(document.querySelector('.poly-replay-view'))window.__polySetReplayGhostVisibility?.(values);});
 window.electron?.onTasToolRequestLoad?.(index=>{if(!document.querySelector('.poly-replay-view')||!Number.isInteger(index))return;const rec=window.__polyReplayRecord?.(index);if(rec)window.electron.setTasRecording(rec.serialize());});
 let lastCam='';if(window.electron?.tasToolFreeCamCoords)setInterval(()=>{try{const coords=document.querySelector('.poly-replay-view')?window.__polyReplayFreeCam?.():document.querySelector('.game-ui')?window.__polyLiveFreeCam?.():{active:false};const key=JSON.stringify(coords);if(key!==lastCam){lastCam=key;window.electron.tasToolFreeCamCoords(coords);}}catch{}},200);
 window.electron?.onTasToolDriveRate?.(p=>window.__setSimSpeed?.(Number(p.rate)||1));
 window.electron?.onTasToolSlowMoRate?.(p=>{if(document.querySelector('.poly-replay-view'))window.__polyReplayRate=Math.max(.05,Math.min(4,Number(p.rate)||1));else window.__setSimSpeed?.(Number(p.rate)||1);});
});
})();
